### ISSUE TITLE
App crashing on startup

### ISSUE THREAD

**Issue by knightry** [notatallshaw/fall_guys_ping_estimate#46]
Crashes on startup. Happy to provide logs if necessary.

```
> python -m fgpe
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\username\scoop\apps\python\current\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\username\scoop\apps\python\current\lib\tkinter\__init__.py", line 814, in callit
    func(*args)
  File "C:\Users\username\scoop\apps\python\current\lib\site-packages\fgpe\overlay.py", line 51, in update_label
    wait_time, update_text = self.get_new_text_callback()
  File "C:\Users\username\scoop\apps\python\current\lib\site-packages\fgpe\__main__.py", line 124, in update_text
    status, connection =  self.reader.get_connection_details()
  File "C:\Users\username\scoop\apps\python\current\lib\site-packages\fgpe\log_reader.py", line 72, in get_connection_details
    self._update_ip_from_log_file()
  File "C:\Users\username\scoop\apps\python\current\lib\site-packages\fgpe\log_reader.py", line 55, in _update_ip_from_log_file
    for line in f:
  File "C:\Users\username\scoop\apps\python\current\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 7153: character maps to <undefined>
```

**Comment by notatallshaw** [comment]
Does it still happen in latest version?

Basically logs started including non-unicode characters, I now ignore decoding errors.

**Comment by notatallshaw** [comment]
Also why did Github not send me this email 🤔, I was having to debug it myself when you already debugged it.

**Comment by knightry** [comment]
Just updated to latest version, will let you know if I see the same issue again.

**Comment by knightry** [comment]
LGTM
