### ISSUE TITLE
fgpe directory not found on new install

### ISSUE THREAD

**Issue by knightry** [notatallshaw/fall_guys_ping_estimate#52]
PS C:\> python -m fgpe
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\fgpe\__main__.py", line 193, in <module>
    logging.basicConfig(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 2040, in basicConfig
    h = FileHandler(filename, mode,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\AppData\\Roaming\\fgpe\\errors.log'

Manually creating `C:\\Users\\user\\AppData\\Roaming\\fgpe` corrected the issue.

**Comment by notatallshaw** [comment]
Thanks for the reporting, I guess at some point I dropped making the directory. 

I definitely just start writing test cases, this would be an easy place to start.

**Comment by notatallshaw** [comment]
Fixed by https://github.com/notatallshaw/fall_guys_ping_estimate/pull/53
